spring:
  application:
    name: cloud-admin
  profiles:
    active: system, cms
  resources:
    static-locations: file:upload-tmp/
  mvc:
    static-path-pattern: /static/**
dubbo:
  protocol:
    name: dubbo
    host: 10.73.
  registry:
    address: zookeeper://localhost:2181
  application:
    name: cloud-admin
server:
  context-path: /admin
  port: 8080
cloud:
  security:
    permit-urls: /static/**
    sessionAge: 7200
    secret: SECRET
logging:
  level:
    com.lyl.study.cloud: DEBUG