# 这个配置在联调环境中不会用到，只有在单模块开发时才起作用
spring:
  application:
    name: cloud-admin-cms
  profiles:
    active: cms
  resources:
    static-locations: file:upload-tmp/
  mvc:
    static-path-pattern: /static/**
dubbo:
  protocol:
    name: dubbo
    host: 10.73.
  registry:
    address: zookeeper://localhost:2181
  application:
    name: cloud-admin
server:
  port: 8080
cloud:
  security:
    permit-urls: /static/**, /cms/resourceEntity/**
    sessionAge: 7200
    secret: SECRET
logging:
  level:
    com.lyl.study.cloud: DEBUG