spring:
  application:
    name: cloud-cms
dubbo:
  scan:
  protocol:
    name: dubbo
  application:
    name: cloud-cms
server:
  context-path: /cms
---
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    host: 10.73.
server:
  port: 8081
cloud:
  resources:
    uploadPath: file:upload-tmp/
    urlPrefix: /cms/static/
    maxImageSize: 5MB
    maxAudioSize: 20MB
    maxVideoSize: ${spring.http.multipart.max-file-size}
  security:
    permit-urls: /static/**
    sessionAge: 7200
    secret: SECRET
logging:
  level:
    com.lyl.study.cloud: DEBUG
spring:
  resources:
    static-locations: ${cloud.resources.uploadPath}
  mvc:
    static-path-pattern: /static/**
  http:
    multipart:
      max-file-size: 100MB
---
spring:
  profiles: beta
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8
#dubbo:
#  registry:
#    address: zookeeper://localhost:2181
#  protocol:
#    host: 10.73
#    port: 4080
#
#logging:
#  level:
#    com.lyl.study.cloud: DEBUG
#debug: true