spring:
  application:
    name: cloud-gateway-web
dubbo:
  protocol:
    name: dubbo
  application:
    name: cloud-gateway-web
server:
  context-path: /gateway
cloud:
  gateway:
    loginUrl: /session/login
    logoutUrl: /session/logout
---
spring:
  profiles: dev
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    host: 192.168.
server:
  port: 8080
cloud:
  security:
    sessionAge: 7200
    secret: SECRET
logging:
  level:
    com.lyl.study.cloud: DEBUG
---
spring:
  profiles: beta
#dubbo:
#  registry:
#    address: zookeeper://localhost:2181
#server:
#  port: 8080