# 这个配置在联调环境中不会用到，只有在单模块开发时才起作用
spring:
  application:
    name: cloud-wxclient-vip
  profiles:
    active: vip
dubbo:
  protocol:
    name: dubbo
#    host: 192.168.
  registry:
    address: zookeeper://localhost:2181
  application:
    name: cloud-admin-system
server:
  port: 8081
cloud:
  security:
    permit-urls: /static/**, /session/verifyCode
    sessionAge: 7200
    secret: SECRET
logging:
  level:
    com.lyl.study.cloud: DEBUG